/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import config.Koneksi;

/**
 *
 * @author KELOMPOK 2 R6Q 2021 - KELOMPOK KKP R8Q 2022
 */
public class LoginForm extends javax.swing.JFrame {

    /** Creates new form LoginForm */
    public LoginForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginContainer = new javax.swing.JPanel();
        loginTopbar = new javax.swing.JPanel();
        loginTitle2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginCard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        visiblePass = new javax.swing.JLabel();
        loginButton = new javax.swing.JLabel();
        resetButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMAK - Halaman Masuk");
        setMinimumSize(new java.awt.Dimension(960, 540));
        setResizable(false);

        loginContainer.setBackground(new java.awt.Color(225, 225, 228));
        loginContainer.setMaximumSize(new java.awt.Dimension(960, 540));
        loginContainer.setMinimumSize(new java.awt.Dimension(960, 540));
        loginContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTopbar.setBackground(new java.awt.Color(36, 36, 39));
        loginTopbar.setMaximumSize(new java.awt.Dimension(960, 70));
        loginTopbar.setMinimumSize(new java.awt.Dimension(960, 70));
        loginTopbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTitle2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        loginTitle2.setForeground(new java.awt.Color(225, 225, 228));
        loginTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle2.setText("SIMAK - Sistem Informasi Manajemen Keuangan");
        loginTitle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTitle2MouseClicked(evt);
            }
        });
        loginTopbar.add(loginTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 948, 68));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/topLogin.jpg"))); // NOI18N
        loginTopbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginContainer.add(loginTopbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        loginCard.setBackground(new java.awt.Color(223, 223, 242));
        loginCard.setMaximumSize(new java.awt.Dimension(480, 460));
        loginCard.setMinimumSize(new java.awt.Dimension(480, 460));
        loginCard.setPreferredSize(new java.awt.Dimension(480, 460));
        loginCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginCardMouseClicked(evt);
            }
        });
        loginCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 130, 216));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        loginCard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 183, 250, 3));

        username.setBackground(new java.awt.Color(223, 223, 242));
        username.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(69, 73, 74));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(null);
        username.setMaximumSize(new java.awt.Dimension(250, 30));
        username.setMinimumSize(new java.awt.Dimension(250, 30));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformednon(evt);
            }
        });
        loginCard.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 155, 250, 30));

        jPanel2.setBackground(new java.awt.Color(0, 130, 216));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        loginCard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 293, 250, 3));

        password.setBackground(new java.awt.Color(223, 223, 242));
        password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(69, 73, 74));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(null);
        password.setMaximumSize(new java.awt.Dimension(250, 30));
        password.setMinimumSize(new java.awt.Dimension(250, 30));
        password.setPreferredSize(new java.awt.Dimension(250, 30));
        loginCard.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 265, -1, -1));

        jLabel1.setBackground(new java.awt.Color(223, 223, 242));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(69, 73, 74));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/account.png"))); // NOI18N
        jLabel1.setLabelFor(username);
        jLabel1.setText("Username");
        jLabel1.setIconTextGap(10);
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 25));
        loginCard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 120, 250, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 73, 74));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/padlock.png"))); // NOI18N
        jLabel2.setText("Password");
        jLabel2.setIconTextGap(10);
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 25));
        loginCard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 230, 250, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 36, 39));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Masuk Sebagai Admin");
        jLabel5.setPreferredSize(new java.awt.Dimension(250, 30));
        loginCard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 50, -1, -1));

        visiblePass.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        visiblePass.setForeground(new java.awt.Color(0, 0, 204));
        visiblePass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visiblePass.setText("Show Password");
        visiblePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visiblePassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                visiblePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                visiblePassMouseExited(evt);
            }
        });
        loginCard.add(visiblePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 305, 250, -1));

        loginButton.setBackground(new java.awt.Color(0, 130, 216));
        loginButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(244, 244, 250));
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButton.setText("LOGIN");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginButton.setOpaque(true);
        loginButton.setPreferredSize(new java.awt.Dimension(100, 35));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        loginCard.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        resetButton.setBackground(new java.awt.Color(0, 130, 216));
        resetButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(244, 244, 250));
        resetButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetButton.setText("RESET");
        resetButton.setOpaque(true);
        resetButton.setPreferredSize(new java.awt.Dimension(100, 35));
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetButtonMouseExited(evt);
            }
        });
        loginCard.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        loginContainer.add(loginCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 130, 216, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/1.jpg"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginContainer.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 480, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformednon(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformednon
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformednon

    private void visiblePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visiblePassMouseClicked
        if (visiblePass.getText().equals("Show Password")){
            visiblePass.setText("Hide Password");
            password.setEchoChar((char)0);
        }else{
            visiblePass.setText("Show Password");
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_visiblePassMouseClicked

    private void visiblePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visiblePassMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_visiblePassMouseEntered

    private void visiblePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visiblePassMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_visiblePassMouseExited

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        username.setText("");
        password.setText("");
        
        username.requestFocus();
    }//GEN-LAST:event_resetButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        Connection conn = Koneksi.getKoneksi();
        String query = "SELECT * FROM users WHERE username='"+username.getText()+"' AND password='"+password.getText()+"'";
        
        try{
            Statement stmt = conn.createStatement();
            ResultSet rest = stmt.executeQuery(query);
            
            if (rest.next()){
                if (username.getText().equals(rest.getString("username")) && password.getText().equals(rest.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Berhasil Masuk, Selamat Datang!");

                    this.dispose();
                    new Dashboard().setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Username atau Password salah!");
            }
            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Koneksi gagal : "+e.getMessage());
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setBackground(new java.awt.Color(7,116,188));
        loginButton.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        loginButton.setBackground(new java.awt.Color(0,130,216));
        loginButton.setForeground(new java.awt.Color(244,244,250));
    }//GEN-LAST:event_loginButtonMouseExited

    private void resetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseEntered
        resetButton.setBackground(new java.awt.Color(7,116,188));
        resetButton.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_resetButtonMouseEntered

    private void resetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseExited
        resetButton.setBackground(new java.awt.Color(0,130,216));
        resetButton.setForeground(new java.awt.Color(244,244,250));
    }//GEN-LAST:event_resetButtonMouseExited

    private void loginCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginCardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginCardMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void loginTitle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTitle2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTitle2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loginButton;
    private javax.swing.JPanel loginCard;
    private javax.swing.JPanel loginContainer;
    private javax.swing.JLabel loginTitle2;
    private javax.swing.JPanel loginTopbar;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel resetButton;
    private javax.swing.JTextField username;
    private javax.swing.JLabel visiblePass;
    // End of variables declaration//GEN-END:variables

}
